#!/bin/sh
# /etc/init.d/startup

PATH=$PATH:/hab/bin

# mount the special pseudo filesytems /proc and /sys
hab pkg exec core/util-linux mount -t proc proc /proc -o nosuid,noexec,nodev
hab pkg exec core/util-linux mount -t sysfs sys /sys -o nosuid,noexec,nodev
# /dev isn't required if we boot without initramfs because the kernel
# will have done this for us but it doesn't hurt
hab pkg exec core/util-linux mount -t devtmpfs dev /dev -o mode=0755,nosuid
hab pkg exec core/coreutils mkdir -p /dev/pts /dev/shm
# /dev/pts contains pseudo-terminals, gid 5 should be the
# tty user group
hab pkg exec core/util-linux mount -t devpts devpts /dev/pts -o mode=0620,gid=5,nosuid,noexec
# /run contains runtime files like pid files and domain sockets
# they don't need to be stored on the disk, we'll store them in RAM
hab pkg exec core/util-linux mount -t tmpfs run /run -o mode=0755,nosuid,nodev
hab pkg exec core/util-linux mount -t tmpfs shm /dev/shm -o mode=1777,nosuid,nodev
# the nosuid,noexec,nodev options are for security reasons and are not
# strictly necessary, you can read about them in the 'mount'
# man page

# the kernel does not read /etc/hostname on it's own
# you need to write it in /proc/sys/kernel/hostname to set it
# don't forget to create this file if you want to give your system a name
if [[ -f /etc/hostname ]]; then
  cat /etc/hostname > /proc/sys/kernel/hostname
fi

# mdev is a mini-udev implementation that
# populates /dev with devices by scanning /sys
# see the util-linux/mdev.c file in the busybox source
# for more information
hab pkg exec core/busybox-static mdev -s
echo $(hab pkg exec core/busybox-static mdev) > /proc/sys/kernel/hotplug

# the "localhost" loopback network interface is
# down at boot, we have to set it 'up' or we won't be able to
# make local network connections
hab pkg exec core/iproute2 ip link set up dev lo

# mounts all filesystems in /etc/fstab
hab pkg exec core/util-linux mount -a
# make the root writable if this hasn't been done already
hab pkg exec core/util-linux mount -o remount,rw /

hab pkg exec core/coreutils chmod ugo+rw /dev/null
hab pkg exec core/coreutils chmod ugo+rw /dev/urandom

